language: node_js
sudo: false

env:
  - SENECA_VER=seneca@1.x.x
  - SENECA_VER=seneca@2.x.x
  - SENECA_VER=seneca@3.x.x
  - SENECA_VER=senecajs/seneca

node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - node_modules

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
